#!/bin/bash

set -euo pipefail

mkdir -p bin

HAILO_RT_HEADER=/usr/include/hailo/hailort.h
BIN_DIR=bin
CXX_FLAGS="-std=c++17 -fPIC -Wall -Werror -O2"

if [ ! -f "$HAILO_RT_HEADER" ]; then
	echo "Unable to find '$HAILO_RT_HEADER'"
	echo "Skipping Hailo support"
	#g++ -c stub.cpp -o $BIN_DIR/stub.o
	#ar rcs $BIN_DIR/cyhailo.a $BIN_DIR/stub.o
	exit 0
fi

echo "Building Hailo support"
g++ $CXX_FLAGS -c hailo.cpp -o $BIN_DIR/hailo.o
g++ $CXX_FLAGS -c defs.cpp -o $BIN_DIR/defs.o
g++ $CXX_FLAGS -c pagealloc.cpp -o $BIN_DIR/pagealloc.o
#ar rcs $BIN_DIR/cyhailo.a $BIN_DIR/hailo.o $BIN_DIR/defs.o
g++ -shared -o $BIN_DIR/libcyclopshailo.so $BIN_DIR/hailo.o $BIN_DIR/pagealloc.o $BIN_DIR/defs.o -lhailort
