#!/bin/bash

# Build and deploy as systemd services.

set -e

if ! grep -q cyclops /etc/group; then
	echo Creating cyclops group
	sudo groupadd --system cyclops
fi

if ! grep -q cyclops /etc/passwd; then
	echo Creating cyclops user
	sudo useradd --system \
		--gid cyclops \
		--create-home \
		--home-dir /var/lib/cyclops \
		--shell /usr/sbin/nologin \
		--comment "Cyclops Camera Security System" \
		cyclops
fi

cd www && npm install && npm run build && cd ..
go build -o bin/cyclops cmd/cyclops/*.go

if [ -f /etc/systemd/system/cyclops.service ]; then
	sudo systemctl stop cyclops
fi

# Always update .service file to latest
sudo cp deployment/services/cyclops.service /etc/systemd/system

sudo systemctl daemon-reload
sudo systemctl enable cyclops

# Copy binaries
sudo cp bin/cyclops /usr/local/bin/cyclops

# Copy NN models
sudo -u cyclops mkdir -p /var/lib/cyclops/models
sudo -u cyclops cp models/* /var/lib/cyclops/models/

# Start service
sudo systemctl start cyclops

# Show status
sudo systemctl status cyclops

