#!/bin/bash
set -euo pipefail

# noble, bookworm, etc.
DISTRO=$(lsb_release -sc)

# eg 1.0.0
VERSION=$(cat VERSION)

rm ../cyclops_* || true

# The top entry in the changelog is the one that will be used for the build.
#dch --distribution "$DISTRO" --local "~$DISTRO" -m "Automated build for $DISTRO"

# This one weird trick!
# If our top changelog entry looks like this:
#   cyclops (1.0.0-0) unstable; urgency=medium
# And we run with "--local 1" for DISTRO=jammy, then we get this:
#   cyclops (1.0.0-1) jammy; urgency=medium
# Which is precisely what we want.
#dch --distribution "$DISTRO" --local 1 -m "Automated build for $DISTRO"

# But hang on, there's an even simpler technique.
# This will modify the top entry, so that it's target is the given distro.
# And it won't change the version number.
#dch --distribution "$DISTRO" -a -m "Automated build for $DISTRO, git revision $(git rev-parse HEAD)"

# BUT.. it turns out that we need the distro name in our .deb name. It's vital for reprepro, and to
# achieve our goal of having a single repo for all distros and architectures.
dch -b --force-distribution --distribution "$DISTRO" --newversion "$VERSION"-1~"$DISTRO" -m "Automated build for $DISTRO, git revision $(git rev-parse HEAD)"

debuild -us -uc -b