#!/bin/bash

set -e

cd ncnn
mkdir -p build
cd build
cmake -DNCNN_SIMPLEOCV=1 -DNCNN_BUILD_EXAMPLES=OFF ..
make -j2

cd ../..

cd Simd
mkdir -p build
cd build
cmake ../prj/cmake
make -j2

cd ../..

cd nnaccel/hailo
./build

cd ../..
