version: "3.2"
services:
  db:
    image: "postgres:14.5-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/proxypg:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: lol
    command: "-c listen_addresses=*"
